### ISSUE TITLE
Map Save

### ISSUE THREAD

**Issue by mdgis** [datakind/ccep_vote_center_siting_tool_beta#11]
Map Print - Can we get the save map to center to what is seen ? not sure of that is super annoying or not - but currently it centers to the left. Also can we hide the choose dataset text (or at least have it styled) also the map legend has lost background. - I'm sure these are separate issues with varying levels of complexity - we can discuss

**Comment by kuanb** [comment]
You mean the blue print button?

**Comment by mdgis** [comment]
Yeah the print button

**Comment by kuanb** [comment]
Can you screen cap? It looks like this to me:
![image](https://user-images.githubusercontent.com/6053396/34996966-029f3258-fa90-11e7-887a-fa2a6a333443.png)

**Comment by kuanb** [comment]
Oh wait misread your issue comment (just waking up), you mean when the button is printed.

I would just update the hacky `printScreen()` function in interface.js

**Comment by mdgis** [comment]
Just seeing this - need to set up alerts for these things. Yeah this is about what is actually printed, if click the button with the map centered on your screen - you will see that it prints the left side of the screen.

**Comment by mdgis** [comment]
Abandoned this
