### ISSUE TITLE
Useless slider Right Side of Map

### ISSUE THREAD

**Issue by mdgis** [datakind/ccep_vote_center_siting_tool_beta#19]
Is this just a css thing ? slider does nothing and is confusing to see. Point me in the right direction and i can do it 👍 

![image](https://user-images.githubusercontent.com/7546047/35184274-8b32954a-fdc1-11e7-875f-23f121808e82.png)

**Comment by mdgis** [comment]
Actually is this something useful on mobile maybe ?

**Comment by kuanb** [comment]
Hrm... Is that always happening on your computer?

If so, then we have an issue where the map element is bigger than the parent div... I have not seen this on my computer. Is this still going on?

**Comment by mdgis** [comment]
I fixed this a while back
